### ISSUE TITLE
Some assets/classes are broken after latest stable update (110451)

### ISSUE THREAD

**Issue by tmbottegal** [Goose-Nest/GT-RevertRebrand#65] opened 2022-01-11 19:11 UTC
![image](https://user-images.githubusercontent.com/38114233/149005560-c21575d0-0ccd-4ba7-89c0-34eb375885f9.png)

As you can see here, pings and reactions appear to be the newer, stinky assets instead of the replacements. (The channel tab shown is just to show that the font is not broken)

![image](https://user-images.githubusercontent.com/38114233/149005591-12835f42-ed3c-4644-a7dd-86366587954a.png)

Another example is the Discord icon itself, and the text above it. Note that the font is not broken.

**I am running:**
_Stable 110451 (c233a73)
BetterDiscord 1.3.0
Host 1.0.9003
Windows 10 64-Bit (10.0.19043)
Revert Rebrand v5.1_

Thanks!

**Comment by Gaming32** [comment] 2022-01-11 20:48
Me and a friend have the same issue

**Comment by jh34ghu43gu** [comment] 2022-01-11 20:59
Things that appear broken I can see:

Mentions
Channel mentions
Reactions
The '@ ON' color for replies
Folders (Not 100% sure on this but it is using the new color now and my un-updated phone app uses the old color so I assume it's broke)

**Comment by SupDos** [comment] 2022-01-11 21:11
there are already some pull requests to fix it #60 #61 #62 and #63, just waiting for them to be merged I think

**Comment by CanadaHonk** [comment] 2022-01-11 21:12
No, they are not valid. Waiting for author to fix. Duplicate of #64, closing. Please always check existing issues first.

**Closed as completed by CanadaHonk** 2022-01-11 21:12 UTC
