### ISSUE TITLE
some do not disturb + idle icons show up as green

### ISSUE THREAD

**Issue by ghost** [Goose-Nest/GT-RevertRebrand#35] opened 2021-06-19 19:15 UTC
seems like it happens in all places where there's a status icon, and is also very random (changes on every refresh from what i can tell)
![image](https://user-images.githubusercontent.com/46719718/122653102-6a120f00-d0f7-11eb-91ec-0fdb3470b1b4.png)
however the typing indicator makes the color revert back to what it's supposed to be
![image](https://user-images.githubusercontent.com/46719718/122653156-bc533000-d0f7-11eb-8a50-6a315558d9d0.png)
idle seems much less likely as i only saw that once, but it still does happen

**Comment by CanadaHonk** [comment] 2021-06-19 19:16
Will investigate.

**Comment by CanadaHonk** [comment] 2021-06-19 19:20
Cannot reproduce, can you ensure it is only this theme and no other themes or plugins?

**Comment by ghost** [comment] 2021-06-19 19:34
i disabled everything except the revert rebrand theme and it seems to have stopped doing it, now i gotta go through everything to see what it is

**Comment by CanadaHonk** [comment] 2021-06-19 19:42
Closing then as it seems like an issue not with this theme.

**Closed as completed by CanadaHonk** 2021-06-19 19:42 UTC
